[CmdletBinding()]
param()

$ErrorActionPreference = "Stop"
$root = Split-Path $PSScriptRoot -Parent
$fabricRoot = Join-Path $root "MKTCI-DATA-AGENT"
$items = [ordered]@{}
$solutionFields = @(
    "crfc2_journeychannelcost",
    "crfc2_custosfixos", "crfc2_custosfixos_base",
    "crfc2_jornadapai", "crfc2_jornadapai_entitytype", "crfc2_jornadapainame",
    "crfc2_channeltotalcost", "crfc2_channeltotalcost_base",
    "crfc2_custototaldajornada", "crfc2_custototaldajornada_base",
    "crfc2_new_channel",
    "crfc2_msdynmkt_journey", "crfc2_msdynmkt_journey_entitytype",
    "crfc2_msdynmkt_journeyname",
    "crfc2_new_cost", "crfc2_new_cost_base",
    "crfc2_journeychannelcost1", "crfc2_journeychannelcostid",
    "crfc2_new_period"
)
$unsupportedFields = @(
    "parent_contactid", "parent_contactid_entitytype",
    "parent_contactidname", "parent_contactidyominame"
)
$portableTableFields = @{
    contact = @("address1_city", "contactid")
    lead = @("leadid", "msdynmkt_customerjourneyid")
    opportunity = @(
        "statecode", "msdynmkt_journeyid", "originatingleadid", "customerid",
        "actualvalue", "estimatedvalue", "opportunityid"
    )
}

function Remove-UnsupportedSchema($node) {
    if ($node -is [array]) {
        return @($node |
            Where-Object {
                $name = $_.display_name
                -not $name -or
                ($name -notin @("CustomSent", "CustomNotSent") -and
                    $name -notin $unsupportedFields -and
                    (-not $name.StartsWith("crfc2_") -or $name -in $solutionFields))
            } |
            ForEach-Object { Remove-UnsupportedSchema $_ })
    }
    if ($node -is [pscustomobject]) {
        $tableName = [string]$node.display_name
        if ($node.type -match "\.table$" -and $portableTableFields.ContainsKey($tableName)) {
            $node.is_selected = $true
            $node.children = @(
                $node.children |
                Where-Object { $_.display_name -in $portableTableFields[$tableName] } |
                ForEach-Object { Remove-UnsupportedSchema $_ }
            )
            return $node
        }
        foreach ($property in $node.PSObject.Properties) {
            $property.Value = Remove-UnsupportedSchema $property.Value
        }
    }
    return $node
}

@(
    @{ Key = "semantic"; Type = "SemanticModel"; Name = "Visão_MKT"; Directory = "Visão_MKT.SemanticModel" },
    @{ Key = "report"; Type = "Report"; Name = "Marketing Report"; Directory = "Dashboard - CX.Report" },
    @{ Key = "agent"; Type = "DataAgent"; Name = "Agente-Jornadas"; Directory = "Agente-Jornadas.DataAgent" }
) | ForEach-Object {
    $directory = Join-Path $fabricRoot $_.Directory
    $files = @(
        Get-ChildItem $directory -Recurse -File -Force |
        Where-Object { $_.FullName -notmatch "[\\/]ontology-" } |
        ForEach-Object {
            $bytes = [IO.File]::ReadAllBytes($_.FullName)
            if ($_.Name -eq "stage_config.json") {
                $config = [Text.Encoding]::UTF8.GetString($bytes) | ConvertFrom-Json
                $config.aiInstructions = $config.aiInstructions.Replace(
                    "2) Ontology: `"DataAgent_CIJ_Ontology`" (for semantic navigation between Journey, Contact, Opportunity, EmailSent, and EmailOpened)`n3) Lakehouse: `"Lakehouse Dataverse vinculado`" (only for ad-hoc validations if necessary)",
                    "2) Lakehouse: `"Lakehouse Dataverse vinculado`" (for schema navigation and ad-hoc validations)"
                )
                $config.aiInstructions += @"


## Lead rules
- Treat a lead as marketing-generated only when it exists in the `lead` table.
- Count leads with the semantic measure `leads generated by marketing`; do not count names or email addresses.
- Use `msdynmkt_customerjourneyid` only to attribute a lead to a journey.
- If a requested lead attribute is unavailable, say so instead of inferring it from contact or opportunity.
"@
                $bytes = [Text.Encoding]::UTF8.GetBytes(
                    ($config | ConvertTo-Json -Depth 10)
                )
            }
            if ($_.Name -eq "datasource.json") {
                $config = [Text.Encoding]::UTF8.GetString($bytes) | ConvertFrom-Json
                if ($config.type -eq "semantic_model") {
                    $config.userDescription = "Curated Direct Lake model for Customer Insights Journeys, marketing leads, contacts, opportunities, journey costs, revenue, and email engagement. Use it for official dashboard KPIs and business answers."
                    $config.dataSourceInstructions = @"
Use this source first for KPIs. Prefer existing measures over recalculating them. Count leads with `leads generated by marketing`; attribute them to journeys only through `lead.msdynmkt_customerjourneyid`. Use `Opp Count`, `Won Revenue`, `MKT Estimated Revenue`, and the ROI measures as defined. Do not invent joins or fields that are not exposed. State the period, filters, and KPI definition in the answer.
"@
                }
                if ($config.type -eq "lakehouse_tables") {
                    $config.userDescription = "Raw Dataverse and Customer Insights Journeys Delta tables in the linked Lakehouse. Use them to inspect event-level records, validate freshness, and investigate sent, delivered, and opened email activity."
                    $config.dataSourceInstructions = @"
Use this source for row-level validation, not as the default KPI source. For email activity use `EmailSent`, `EmailDelivered`, and `EmailOpened`; relate events by `CustomerJourneyId` and `ContactId` when available. Use `Timestamp` for event time. The `lead` table is intentionally limited to `leadid` and `msdynmkt_customerjourneyid`. Do not query optional Custom event tables unless they are present, and never infer delivery or opening from a sent event.
"@
                }
                $config = Remove-UnsupportedSchema $config
                if ($config.metadata.csdl_relationships) {
                    $relationships = $config.metadata.csdl_relationships | ConvertFrom-Json
                    $config.metadata.csdl_relationships = @(
                        $relationships |
                        Where-Object { $_.FromTable -notin @("CustomSent", "CustomNotSent") }
                    ) | ConvertTo-Json -Compress
                }
                $bytes = [Text.Encoding]::UTF8.GetBytes(
                    ($config | ConvertTo-Json -Depth 100)
                )
            }
            @{
                path = $_.FullName.Substring($directory.Length).TrimStart(
                    [IO.Path]::DirectorySeparatorChar,
                    [IO.Path]::AltDirectorySeparatorChar
                ).Replace("\", "/")
                content = [Convert]::ToBase64String($bytes)
            }
        }
    )
    $items[$_.Key] = @{
        type = $_.Type
        displayName = $_.Name
        files = $files
    }
}

$payload = @{
    solution = [Convert]::ToBase64String(
        [IO.File]::ReadAllBytes(
            (Join-Path $fabricRoot "FabricCIJourneyDashboardandAgents_1_0_0_2_managed.zip")
        )
    )
    items = $items
} | ConvertTo-Json -Depth 10 -Compress

$input = [IO.MemoryStream]::new([Text.Encoding]::UTF8.GetBytes($payload))
$output = [IO.MemoryStream]::new()
$gzip = [IO.Compression.GZipStream]::new($output, [IO.Compression.CompressionLevel]::Optimal, $true)
try {
    $input.CopyTo($gzip)
} finally {
    $gzip.Dispose()
    $input.Dispose()
}
$encoded = [Convert]::ToBase64String($output.ToArray())
$output.Dispose()

$target = Join-Path $PSScriptRoot "backend/payload.ts"
New-Item (Split-Path $target -Parent) -ItemType Directory -Force | Out-Null
"export const payloadGzipBase64 = '$encoded';`n" |
    Set-Content $target -Encoding utf8 -NoNewline
Write-Host $target
